[update]
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
]

[[repos]]
repo = "https://github.com/rbubley/mirrors-prettier"
rev = "9337a74165b178ae2c766f60bee7252a0f06f3e8" # frozen: v3.9.5
hooks = [
  { id = "prettier" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "bee27e3a4fd1ea2111cf90ab89cd076c870fce14" # frozen: v1.48.0
hooks = [
  { id = "typos" },
]

[[repos]]
repo = "https://github.com/python-jsonschema/check-jsonschema"
rev = "6b63472e72e1a91ed8a2f6d483790dfb644fa1d3" # frozen: 0.37.4
hooks = [
  { id = "check-github-workflows" },
  { id = "check-renovate" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "914e7df21a07ef503a81201c76d2b11c789d3fca" # frozen: v1.7.12
hooks = [
  { id = "actionlint" },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "64a97fb7fa63188393d3215c6e312f5f9c6d0f78" # frozen: v1.27.0
hooks = [
  { id = "zizmor", args = ["--fix=safe"] },
]

[[repos]]
repo = "https://github.com/compwa/taplo-pre-commit"
rev = "ade0f95ddcf661c697d4670d2cfcbe95d0048a0a" # frozen: v0.9.3
hooks = [
  { id = "taplo-format" },
]

[[repos]]
repo = "https://github.com/golangci/golangci-lint"
rev = "c0d3ddc9cf3faa61a4e378e879ece580256d76e5" # frozen: v2.12.2
hooks = [
  { id = "golangci-lint-full" },
]

[[repos]]
repo = "https://github.com/aleksac/hadolint-py"
rev = "458cb25edf664682e3e856a53a2f9af33e068297" # frozen: v2.14.0
hooks = [
  { id = "hadolint" },
]
